In [3]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'pandas'

# Exploring Csutomer_Behavior Data

In [ ]:
customer_data=pd.read_csv("customer_shopping_behavior.csv")

In [ ]:
customer_data.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
print("the Numbers of Rows in data are " , customer_data.shape[0])
print("the Numbers of Columns in data are " , customer_data.shape[1])

the Numbers of Rows in data are  3900
the Numbers of Columns in data are  18

In [ ]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [ ]:
customer_data.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

# Checking The Null Values and Duplicated Values

In [ ]:
customer_data.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
customer_data.duplicated().sum()

np.int64(0)

In [ ]:
customer_data=customer_data.dropna()

In [ ]:
customer_data.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
customer_data.isna().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

# Exploring The Numbers of unique Values in each Column for object Columns only

In [ ]:
customer_data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

# getting only the object Columns Only

In [ ]:
object_Customer_col=customer_data.select_dtypes(include='object')

In [ ]:
object_Customer_col.columns

Index(['Gender', 'Item Purchased', 'Category', 'Location', 'Size', 'Color',
       'Season', 'Subscription Status', 'Shipping Type', 'Discount Applied',
       'Promo Code Used', 'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [ ]:
object_Customer_col.head()

,Gender,Item Purchased,Category,Location,Size,Color,Season,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Payment Method,Frequency of Purchases
0,Male,Blouse,Clothing,Kentucky,L,Gray,Winter,Yes,Express,Yes,Yes,Venmo,Fortnightly
1,Male,Sweater,Clothing,Maine,L,Maroon,Winter,Yes,Express,Yes,Yes,Cash,Fortnightly
2,Male,Jeans,Clothing,Massachusetts,S,Maroon,Spring,Yes,Free Shipping,Yes,Yes,Credit Card,Weekly
3,Male,Sandals,Footwear,Rhode Island,M,Maroon,Spring,Yes,Next Day Air,Yes,Yes,PayPal,Weekly
4,Male,Blouse,Clothing,Oregon,M,Turquoise,Spring,Yes,Free Shipping,Yes,Yes,PayPal,Annually

In [ ]:
for i in object_Customer_col.columns:
    num_unique=object_Customer_col[i].nunique()
    print(f"the number of unique_Value is {num_unique}")

the number of unique_Value is 2
the number of unique_Value is 25
the number of unique_Value is 4
the number of unique_Value is 50
the number of unique_Value is 4
the number of unique_Value is 25
the number of unique_Value is 4
the number of unique_Value is 2
the number of unique_Value is 6
the number of unique_Value is 2
the number of unique_Value is 2
the number of unique_Value is 6
the number of unique_Value is 7

In [ ]:
for i in object_Customer_col.columns:
    unique_values=object_Customer_col[i].unique()
    print(f"the unique_Value for {i} is {unique_values}")

the unique_Value for Gender is ['Male' 'Female']
the unique_Value for Item Purchased is ['Blouse' 'Sweater' 'Jeans' 'Sandals' 'Sneakers' 'Shirt' 'Shorts' 'Coat'
 'Handbag' 'Shoes' 'Dress' 'Skirt' 'Sunglasses' 'Pants' 'Jacket' 'Hoodie'
 'Jewelry' 'T-shirt' 'Scarf' 'Hat' 'Socks' 'Backpack' 'Belt' 'Boots'
 'Gloves']
the unique_Value for Category is ['Clothing' 'Footwear' 'Outerwear' 'Accessories']
the unique_Value for Location is ['Kentucky' 'Maine' 'Massachusetts' 'Rhode Island' 'Oregon' 'Wyoming'
 'Montana' 'Louisiana' 'West Virginia' 'Missouri' 'Arkansas' 'Hawaii'
 'Delaware' 'New Hampshire' 'New York' 'Alabama' 'Mississippi'
 'North Carolina' 'California' 'Oklahoma' 'Florida' 'Texas' 'Nevada'
 'Kansas' 'Colorado' 'North Dakota' 'Illinois' 'Indiana' 'Arizona'
 'Alaska' 'Tennessee' 'Ohio' 'New Jersey' 'Vermont' 'New Mexico'
 'South Carolina' 'Idaho' 'Pennsylvania' 'Connecticut' 'Utah' 'Virginia'
 'Georgia' 'Nebraska' 'Iowa' 'South Dakota' 'Minnesota' 'Maryland'
 'Washington' 'Wisconsin' 'Michigan']
the unique_Value for Size is ['L' 'S' 'M' 'XL']
the unique_Value for Color is ['Gray' 'Maroon' 'Turquoise' 'White' 'Charcoal' 'Silver' 'Pink' 'Purple'
 'Olive' 'Gold' 'Violet' 'Teal' 'Lavender' 'Black' 'Green' 'Peach' 'Red'
 'Cyan' 'Brown' 'Beige' 'Orange' 'Indigo' 'Yellow' 'Magenta' 'Blue']
the unique_Value for Season is ['Winter' 'Spring' 'Summer' 'Fall']
the unique_Value for Subscription Status is ['Yes' 'No']
the unique_Value for Shipping Type is ['Express' 'Free Shipping' 'Next Day Air' 'Standard' '2-Day Shipping'
 'Store Pickup']
the unique_Value for Discount Applied is ['Yes' 'No']
the unique_Value for Promo Code Used is ['Yes' 'No']
the unique_Value for Payment Method is ['Venmo' 'Cash' 'Credit Card' 'PayPal' 'Bank Transfer' 'Debit Card']
the unique_Value for Frequency of Purchases is ['Fortnightly' 'Weekly' 'Annually' 'Quarterly' 'Bi-Weekly' 'Monthly'
 'Every 3 Months']

# getting only the numeric Columns Only

identify the Outliers for each Cols

In [ ]:
numeric_cols =customer_data.select_dtypes(exclude='object')

In [ ]:
numeric_cols.shape

(3863, 5)

In [ ]:
for x in numeric_cols.columns:
    q1 = numeric_cols[x].quantile(0.25)
    q3 = numeric_cols[x].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    max_bound = q3 + 1.5 * iqr
    
    # تأكد من المحاذاة الصحيحة هنا (4 مسافات)
    numeric_cols_outliers = numeric_cols[(numeric_cols[x] >= lower_bound) & (numeric_cols[x] <= max_bound)]

In [ ]:
print("the Numbers of Rows in data are " , numeric_cols_outliers.shape[0])
print("the Numbers of Columns in data are " , numeric_cols_outliers.shape[1])

the Numbers of Rows in data are  3863
the Numbers of Columns in data are  5

In [ ]:
numeric_cols_outliers.head()

   Customer ID  Age  Purchase Amount (USD)  Review Rating  Previous Purchases
0            1   55                     53            3.1                  14
1            2   19                     64            3.1                   2
2            3   50                     73            3.1                  23
3            4   21                     90            3.5                  49
4            5   45                     49            2.7                  31

# merging the object table and numeric table after Checking all we need

In [ ]:
new_customer_beahvior=pd.concat([object_Customer_col,numeric_cols_outliers],axis =1)

In [ ]:

new_customer_beahvior = new_customer_beahvior.rename(columns={'Purchase Amount (USD)': 'Purchase_Amount_USD'})

In [ ]:
new_customer_beahvior.head()

,Gender,Item Purchased,Category,Location,Size,Color,Season,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Payment Method,Frequency of Purchases,Customer ID,Age,Purchase_Amount_USD,Review Rating,Previous Purchases
0,Male,Blouse,Clothing,Kentucky,L,Gray,Winter,Yes,Express,Yes,Yes,Venmo,Fortnightly,1,55,53,3.1,14
1,Male,Sweater,Clothing,Maine,L,Maroon,Winter,Yes,Express,Yes,Yes,Cash,Fortnightly,2,19,64,3.1,2
2,Male,Jeans,Clothing,Massachusetts,S,Maroon,Spring,Yes,Free Shipping,Yes,Yes,Credit Card,Weekly,3,50,73,3.1,23
3,Male,Sandals,Footwear,Rhode Island,M,Maroon,Spring,Yes,Next Day Air,Yes,Yes,PayPal,Weekly,4,21,90,3.5,49
4,Male,Blouse,Clothing,Oregon,M,Turquoise,Spring,Yes,Free Shipping,Yes,Yes,PayPal,Annually,5,45,49,2.7,31

In [ ]:
new_customer_beahvior.head()

,Gender,Item Purchased,Category,Location,Size,Color,Season,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Payment Method,Frequency of Purchases,Customer ID,Age,Purchase_Amount_USD,Review Rating,Previous Purchases
0,Male,Blouse,Clothing,Kentucky,L,Gray,Winter,Yes,Express,Yes,Yes,Venmo,Fortnightly,1,55,53,3.1,14
1,Male,Sweater,Clothing,Maine,L,Maroon,Winter,Yes,Express,Yes,Yes,Cash,Fortnightly,2,19,64,3.1,2
2,Male,Jeans,Clothing,Massachusetts,S,Maroon,Spring,Yes,Free Shipping,Yes,Yes,Credit Card,Weekly,3,50,73,3.1,23
3,Male,Sandals,Footwear,Rhode Island,M,Maroon,Spring,Yes,Next Day Air,Yes,Yes,PayPal,Weekly,4,21,90,3.5,49
4,Male,Blouse,Clothing,Oregon,M,Turquoise,Spring,Yes,Free Shipping,Yes,Yes,PayPal,Annually,5,45,49,2.7,31

In [ ]:
new_customer_beahvior.shape

(3863, 18)

In [ ]:
cleaning_data = "new_customer_beahvior.csv"
new_customer_beahvior.to_csv(cleaning_data, index=False)

# Connecting to sql server

In [ ]:
! pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in d:\jupypter\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in d:\jupypter\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in d:\jupypter\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\jupypter\lib\site-packages (from sqlalchemy) (4.15.0)

In [ ]:
from sqlalchemy import create_engine
import urllib.parse

csv_file_path = "D:\\customer_beah_project\\new_customer_beahvior.csv"
table_name = "Customer_Behavior"

server_name = r"DESKTOP-1I8OGM7\SQLEXPRESS"
database_name = "Customer_beahvior_vs"

connection_string = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={server_name};"
    f"DATABASE={database_name};"
    "Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(connection_string)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

try:
    # 4. قراءة ملف CSV وتحميله في الذاكرة
    print("⏳ جاري قراءة ملف الـ CSV...")
    df = pd.read_csv(csv_file_path)
    
    # 5. نقل البيانات بالكامل إلى SQL Server
    print(f"🚀 جاري نقل البيانات إلى جدول [{table_name}]...")
    # if_exists='replace' معناها لو الجدول موجود هيمسحه ويعمله من جديد. لو عايزه يزود عليه غيرها لـ 'append'
    df.to_sql(table_name, con=engine, if_exists='replace', index=False)
    
    print("✅ تم نقل البيانات بنجاح وبدون أي مشاكل!")

except Exception as e:
    print(f"❌ حصلت مشكلة أثناء النقل: {e}")

⏳ جاري قراءة ملف الـ CSV...
🚀 جاري نقل البيانات إلى جدول [Customer_Behavior]...

d:\Jupypter\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

✅ تم نقل البيانات بنجاح وبدون أي مشاكل!